// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#include "../ui.h"

void ui_ScreenPlay_screen_init(void)
{
    ui_ScreenPlay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPlay, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCover = lv_img_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ImageCover, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_ImageCover, LV_SIZE_CONTENT);    /// 288
    lv_obj_set_align(ui_ImageCover, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCover, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCover, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcVolumen = lv_arc_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ArcVolumen, 465);
    lv_obj_set_height(ui_ArcVolumen, 465);
    lv_obj_set_align(ui_ArcVolumen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ArcVolumen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ArcVolumen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_value(ui_ArcVolumen, 77);
    lv_obj_set_style_arc_color(ui_ArcVolumen, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVolumen, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcVolumen, lv_color_hex(0xEAEAEB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVolumen, 120, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_ArcVolumen, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ButtonScrPlay1 = lv_btn_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ButtonScrPlay1, 100);
    lv_obj_set_height(ui_ButtonScrPlay1, 50);
    lv_obj_set_x(ui_ButtonScrPlay1, -167);
    lv_obj_set_y(ui_ButtonScrPlay1, -3);
    lv_obj_set_align(ui_ButtonScrPlay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScrPlay1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScrPlay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SongInfoPlay = lv_obj_create(ui_ScreenPlay);
    lv_obj_set_width(ui_SongInfoPlay, 294);
    lv_obj_set_height(ui_SongInfoPlay, 53);
    lv_obj_set_x(ui_SongInfoPlay, -1);
    lv_obj_set_y(ui_SongInfoPlay, 167);
    lv_obj_set_align(ui_SongInfoPlay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SongInfoPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SongInfoPlay, lv_color_hex(0x180202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongInfoPlay, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SongInfoPlay, lv_color_hex(0x5A5959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SongInfoPlay, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SongInfoPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SongInfoPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SongInfoPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimer = lv_label_create(ui_SongInfoPlay);
    lv_obj_set_width(ui_LabelTimer, 59);
    lv_obj_set_height(ui_LabelTimer, 18);
    lv_obj_set_x(ui_LabelTimer, 113);
    lv_obj_set_y(ui_LabelTimer, 16);
    lv_obj_set_align(ui_LabelTimer, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelTimer, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_LabelTimer, "-00:00");
    lv_obj_set_style_text_color(ui_LabelTimer, lv_color_hex(0xE5E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTimer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeSlider = lv_slider_create(ui_SongInfoPlay);
    lv_obj_set_width(ui_TimeSlider, 218);
    lv_obj_set_height(ui_TimeSlider, 10);
    lv_obj_set_x(ui_TimeSlider, -29);
    lv_obj_set_y(ui_TimeSlider, 16);
    lv_obj_set_align(ui_TimeSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeSlider, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TimeSlider, lv_color_hex(0xA8A8AF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_TimeSlider, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_TimeSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSongInfoPlay = lv_label_create(ui_SongInfoPlay);
    lv_obj_set_width(ui_LabelSongInfoPlay, 278);
    lv_obj_set_height(ui_LabelSongInfoPlay, 25);
    lv_obj_set_x(ui_LabelSongInfoPlay, 0);
    lv_obj_set_y(ui_LabelSongInfoPlay, -9);
    lv_obj_set_align(ui_LabelSongInfoPlay, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelSongInfoPlay, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelSongInfoPlay, "\\ºªmucho texto mucho textoo texto muchísimo ");
    lv_obj_set_style_text_color(ui_LabelSongInfoPlay, lv_color_hex(0xE5E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSongInfoPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSongInfoPlay, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSongInfoPlay, &ui_font_opensansreg22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSongInfoPlay1 = lv_label_create(ui_SongInfoPlay);
    lv_obj_set_width(ui_LabelSongInfoPlay1, 278);
    lv_obj_set_height(ui_LabelSongInfoPlay1, 28);
    lv_obj_set_x(ui_LabelSongInfoPlay1, 1);
    lv_obj_set_y(ui_LabelSongInfoPlay1, 36);
    lv_obj_set_align(ui_LabelSongInfoPlay1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelSongInfoPlay1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelSongInfoPlay1, "mucho texto mucho texto mucho texto mucho texto");
    lv_obj_set_style_text_color(ui_LabelSongInfoPlay1, lv_color_hex(0xE5E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSongInfoPlay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSongInfoPlay1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSongInfoPlay1, &ui_font_opensansreg22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPlayingInfo = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelPlayingInfo, 196);
    lv_obj_set_height(ui_LabelPlayingInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPlayingInfo, 0);
    lv_obj_set_y(ui_LabelPlayingInfo, -186);
    lv_obj_set_align(ui_LabelPlayingInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPlayingInfo, "PlayingInfo");
    lv_obj_add_flag(ui_LabelPlayingInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPlayingInfo, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPlayingInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPlayingInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPlayingInfo, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelActualPlayer = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelActualPlayer, 179);
    lv_obj_set_height(ui_LabelActualPlayer, 18);
    lv_obj_set_x(ui_LabelActualPlayer, -4);
    lv_obj_set_y(ui_LabelActualPlayer, 210);
    lv_obj_set_align(ui_LabelActualPlayer, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelActualPlayer, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_LabelActualPlayer, "Actual Player ");
    lv_obj_set_style_text_color(ui_LabelActualPlayer, lv_color_hex(0xE5E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelActualPlayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelActualPlayer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelActualPlayer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelActualPlayer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelActualPlayer, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelActualPlayer, 140, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonScrPlay1, ui_event_ButtonScrPlay1, LV_EVENT_ALL, NULL);

}
