// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#include "../ui.h"

void ui_ScreenClock_screen_init(void)
{
    ui_ScreenClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenClock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherIcon = lv_img_create(ui_ScreenClock);
    lv_img_set_src(ui_WeatherIcon, &ui_img_clear_png);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherIcon, 0);
    lv_obj_set_y(ui_WeatherIcon, -162);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sec = lv_img_create(ui_ScreenClock);
    lv_img_set_src(ui_sec, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, 0);
    lv_obj_set_y(ui_sec, -67);
    lv_obj_set_align(ui_sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_sec, 15, 155);
    lv_img_set_angle(ui_sec, 300);
    lv_img_set_zoom(ui_sec, 300);

    ui_min = lv_img_create(ui_ScreenClock);
    lv_img_set_src(ui_min, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 0);
    lv_obj_set_y(ui_min, -75);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_min, 9, 153);
    lv_img_set_zoom(ui_min, 300);

    ui_hour = lv_img_create(ui_ScreenClock);
    lv_img_set_src(ui_hour, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, 0);
    lv_obj_set_y(ui_hour, -45);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_hour, 9, 93);
    lv_img_set_zoom(ui_hour, 300);

    ui_LabelScreenClock = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_LabelScreenClock, 196);
    lv_obj_set_height(ui_LabelScreenClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenClock, 0);
    lv_obj_set_y(ui_LabelScreenClock, 189);
    lv_obj_set_align(ui_LabelScreenClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenClock, "00:00");
    lv_obj_set_style_text_color(ui_LabelScreenClock, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelScreenClock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenClock, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDescription = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_WeatherDescription, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDescription, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDescription, 0);
    lv_obj_set_y(ui_WeatherDescription, -74);
    lv_obj_set_align(ui_WeatherDescription, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherDescription, "Mu fresquito");
    lv_obj_set_style_text_color(ui_WeatherDescription, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherDescription, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherDescription, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherDescription, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherMaxMin = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_WeatherMaxMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherMaxMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherMaxMin, 0);
    lv_obj_set_y(ui_WeatherMaxMin, 88);
    lv_obj_set_align(ui_WeatherMaxMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherMaxMin, "Min 00ºC - Max 00ºC");
    lv_obj_set_style_text_color(ui_WeatherMaxMin, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherMaxMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherMaxMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherMaxMin, &ui_font_Madeleine30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDegrees = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_WeatherDegrees, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDegrees, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDegrees, 0);
    lv_obj_set_y(ui_WeatherDegrees, 136);
    lv_obj_set_align(ui_WeatherDegrees, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherDegrees, "25ºC");
    lv_obj_set_style_text_color(ui_WeatherDegrees, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherDegrees, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WeatherDegrees, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherDegrees, &ui_font_Madeleine60, LV_PART_MAIN | LV_STATE_DEFAULT);

}
