// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#include "../ui.h"

void ui_ScreenNavigate_screen_init(void)
{
    ui_ScreenNavigate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenNavigate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenNavigate, lv_color_hex(0x363434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenNavigate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenNavigate = lv_label_create(ui_ScreenNavigate);
    lv_obj_set_width(ui_LabelScreenNavigate, 196);
    lv_obj_set_height(ui_LabelScreenNavigate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenNavigate, 0);
    lv_obj_set_y(ui_LabelScreenNavigate, -191);
    lv_obj_set_align(ui_LabelScreenNavigate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenNavigate, "Play List");
    lv_obj_set_style_text_color(ui_LabelScreenNavigate, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenNavigate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelScreenNavigate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenNavigate, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}
