// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#ifndef _ROT_LMS_UI_H
#define _ROT_LMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void cover_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenPlay
void ui_ScreenPlay_screen_init(void);
extern lv_obj_t * ui_ScreenPlay;
extern lv_obj_t * ui_ImageCover;
extern lv_obj_t * ui_ArcVolumen;
void ui_event_ButtonScrPlay1(lv_event_t * e);
extern lv_obj_t * ui_ButtonScrPlay1;
extern lv_obj_t * ui_SongInfoPlay;
extern lv_obj_t * ui_LabelTimer;
extern lv_obj_t * ui_TimeSlider;
extern lv_obj_t * ui_LabelSongInfoPlay;
extern lv_obj_t * ui_LabelSongInfoPlay1;
extern lv_obj_t * ui_LabelPlayingInfo;
extern lv_obj_t * ui_LabelActualPlayer;
// SCREEN: ui_ScreenNavigate
void ui_ScreenNavigate_screen_init(void);
extern lv_obj_t * ui_ScreenNavigate;
extern lv_obj_t * ui_LabelScreenNavigate;
// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
extern lv_obj_t * ui_ScreenClock;
extern lv_obj_t * ui_WeatherIcon;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_LabelScreenClock;
extern lv_obj_t * ui_WeatherDescription;
extern lv_obj_t * ui_WeatherMaxMin;
extern lv_obj_t * ui_WeatherDegrees;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_clear_png);    // assets\Clear.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets\clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets\clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets\clockwise_hour.png

LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_madeleine22);
LV_FONT_DECLARE(ui_font_Madeleine30);
LV_FONT_DECLARE(ui_font_Madeleine40);
LV_FONT_DECLARE(ui_font_Madeleine60);
LV_FONT_DECLARE(ui_font_monos100);
LV_FONT_DECLARE(ui_font_montse100);
LV_FONT_DECLARE(ui_font_montse120);
LV_FONT_DECLARE(ui_font_oneslot100);
LV_FONT_DECLARE(ui_font_oneslot120);
LV_FONT_DECLARE(ui_font_opensans);
LV_FONT_DECLARE(ui_font_opensans22);
LV_FONT_DECLARE(ui_font_opensansreg22);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
