// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btn_scrPlay1_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
